name: controle_financeiro
description: "App de controle financeiro pessoal premium."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.7

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # Export
  csv: ^6.0.0
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.1.4
  path_provider: ^2.1.4

  # Auth Social
  google_sign_in: ^6.2.1

  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.3
  shimmer: ^3.0.0
  gap: ^3.0.1
  cupertino_icons: ^1.0.8

  # Media
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  # Utils
  intl: 0.20.2
  uuid: ^4.4.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  collection: ^1.18.0

  # Notifications
  flutter_local_notifications: ^17.2.4
  flutter_timezone: ^1.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.3
  freezed: ^2.5.2
  mocktail: ^1.0.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # assets: (descomentar quando adicionar arquivos reais)
  # - assets/images/
  # - assets/icons/
  # - assets/animations/

